2025-07-29 16:18:50.960 | INFO     | __main__:main:37 - Starting FAISS index build process
2025-07-29 16:18:50.960 | INFO     | __main__:main:50 - Initializing SFDC client...
2025-07-29 16:18:50.960 | INFO     | src.data_extraction.sfdc_client:_connect:34 - Connecting to Salesforce with:
2025-07-29 16:18:50.960 | INFO     | src.data_extraction.sfdc_client:_connect:35 -   Username: jaykarki@algo.com
2025-07-29 16:18:50.960 | INFO     | src.data_extraction.sfdc_client:_connect:36 -   Login URL: https://login.salesforce.com
2025-07-29 16:18:50.960 | INFO     | src.data_extraction.sfdc_client:_connect:37 -   Domain: login
2025-07-29 16:18:50.960 | INFO     | src.data_extraction.sfdc_client:_connect:38 -   API Version: 58.0
2025-07-29 16:18:50.961 | INFO     | src.data_extraction.sfdc_client:_connect:39 -   Security Token: ************************
2025-07-29 16:18:52.380 | INFO     | src.data_extraction.sfdc_client:_connect:49 - Successfully connected to Salesforce
2025-07-29 16:18:52.718 | INFO     | src.data_extraction.sfdc_client:test_connection:207 - Salesforce connection test successful
2025-07-29 16:18:52.718 | INFO     | __main__:main:58 - Initializing text processor...
2025-07-29 16:18:52.719 | INFO     | __main__:main:61 - Initializing vector database...
2025-07-29 16:18:52.719 | INFO     | __main__:main:65 - Extracting case data from Salesforce...
2025-07-29 16:18:52.939 | ERROR    | src.data_extraction.sfdc_client:get_case_data_batch:135 - Error in batch extraction: Malformed request https://algoleap-5e-dev-ed.develop.my.salesforce.com/services/data/v58.0/query/?q=%0A++++++++SELECT+Id%2C+CaseNumber%2C+CreatedDate%2C+LastModifiedDate%2C+Status%2C+Priority%2C+Origin%2C+Type%2C+Reason%2C+Case_Number%2C+Subject_Description%2C+Description_Description%2C+Issue_Plain_Text%2C+Cause_Plain_Text%2C+Resolution_Plain_Text%2C+Status_Text%2C+TextBody%0A++++++++FROM+Case+%0A++++++++WHERE+CreatedDate+%3E%3D+2023-07-30T16%3A18%3A52.000%2B0000+%0A++++++++++AND+CreatedDate+%3C%3D+2025-07-29T16%3A18%3A52.000%2B0000%0A++++++++++AND+Status+%21%3D+%27Deleted%27%0A++++++++ORDER+BY+CreatedDate+DESC%0A++++++++. Response content: [{'message': "\nPriority, Origin, Type, Reason, Case_Number, Subject_Description\n                                ^\nERROR at Row:1:Column:95\nNo such column 'Case_Number' on entity 'Case'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.", 'errorCode': 'INVALID_FIELD'}]
2025-07-29 16:18:52.940 | ERROR    | __main__:main:142 - Error during index build: Malformed request https://algoleap-5e-dev-ed.develop.my.salesforce.com/services/data/v58.0/query/?q=%0A++++++++SELECT+Id%2C+CaseNumber%2C+CreatedDate%2C+LastModifiedDate%2C+Status%2C+Priority%2C+Origin%2C+Type%2C+Reason%2C+Case_Number%2C+Subject_Description%2C+Description_Description%2C+Issue_Plain_Text%2C+Cause_Plain_Text%2C+Resolution_Plain_Text%2C+Status_Text%2C+TextBody%0A++++++++FROM+Case+%0A++++++++WHERE+CreatedDate+%3E%3D+2023-07-30T16%3A18%3A52.000%2B0000+%0A++++++++++AND+CreatedDate+%3C%3D+2025-07-29T16%3A18%3A52.000%2B0000%0A++++++++++AND+Status+%21%3D+%27Deleted%27%0A++++++++ORDER+BY+CreatedDate+DESC%0A++++++++. Response content: [{'message': "\nPriority, Origin, Type, Reason, Case_Number, Subject_Description\n                                ^\nERROR at Row:1:Column:95\nNo such column 'Case_Number' on entity 'Case'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.", 'errorCode': 'INVALID_FIELD'}]
